#ifndef ORAVI_VERSION_HPP_
#define ORAVI_VERSION_HPP_

#define ORAVI_VERSION "0.1.0-alpha+83fcc68"
#define ORAVI_VERSION_CORE "0.1.0"
#define ORAVI_VERSION_RELEASE "alpha"
#define ORAVI_VERSION_BUILD "83fcc68"

#endif // ORAVI_VERSION_HPP_
