if(CLANGFORMAT_EXECUTABLE AND NOT EXISTS "${CLANGFORMAT_EXECUTABLE}")
  set(CLANGFORMAT_EXECUTABLE "notfound" CACHE PATH FORCE "")
endif()

find_program(CLANGFORMAT_EXECUTABLE NAMES clang-format)

if(CLANGFORMAT_EXECUTABLE)
  execute_process(COMMAND ${CLANGFORMAT_EXECUTABLE} "--version" OUTPUT_VARIABLE CLANGFORMAT_VERSION OUTPUT_STRIP_TRAILING_WHITESPACE)
  string(REGEX REPLACE "clang-format version" "" CLANGFORMAT_VERSION "${CLANGFORMAT_VERSION}")
  string(STRIP CLANGFORMAT_VERSION CLANGFORMAT_VERSION)
endif()

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(ClangFormat DEFAULT_MSG CLANGFORMAT_EXECUTABLE CLANGFORMAT_VERSION)

