if(CLANGTIDY_EXECUTABLE AND NOT EXISTS "${CLANGTIDY_EXECUTABLE}")
  set(CLANGTIDY_EXECUTABLE "notfound" CACHE PATH FORCE "")
endif()

find_program(CLANGTIDY_EXECUTABLE NAMES clang-tidy)

if(CLANGTIDY_EXECUTABLE)
  execute_process(COMMAND ${CLANGTIDY_EXECUTABLE} "--version" OUTPUT_VARIABLE CLANGTIDY_VERSION OUTPUT_STRIP_TRAILING_WHITESPACE)
  string(REGEX REPLACE "LLVM version" "" CLANGTIDY_VERSION "${CLANGTIDY_VERSION}")
  string(STRIP CLANGTIDY_VERSION CLANGTIDY_VERSION)
endif()

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(ClangTidy DEFAULT_MSG CLANGTIDY_EXECUTABLE CLANGTIDY_VERSION)

