name: Development
on:
  push:
    branches:
      - 'develop'
      - 'development'
  pull_request:
    branches:
      - 'develop'
      - 'development'

jobs:
  complete:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
    steps:
      - name: dependencies
        run: sudo apt-get install -y clang-format clang-tidy cppcheck gcovr
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: configure
        run: mkdir ./build && cmake -S . -B ./build -DCMAKE_BUILD_TYPE=Debug
      - name: compile
        run: cmake --build ./build
      - name: tests
        run: cd ./build && ctest -VV
  minimal:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-latest, windows-latest ]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: configure
        run: mkdir ./build && cmake -S . -B ./build -DCMAKE_BUILD_TYPE=Debug -DENABLE_STATIC_ANALYSIS=OFF -DBUILD_DOCS=OFF -DENABLE_COVERAGE=OFF -DENABLE_PROFILING=OFF
      - name: compile
        run: cmake --build ./build
      - name: tests
        run: cd ./build && ctest -VV
